### ISSUE TITLE
Waterfox Third Generation language settings can't add languages?

### ISSUE THREAD

**Issue by candrapersada** [hawkeye116477/LanguagePacksForWaterfox#3]
why can't add languages? for windows
![asasa](https://user-images.githubusercontent.com/36833664/103323029-7a63fe00-4a73-11eb-8280-b63c7d80dcd2.PNG)

**Comment by hawkeye116477** [comment]
It's not case for me. You should write that on https://github.com/MrAlex94/Waterfox/issues. However it's probably disabled, because language packages made for Firefox might become incompatible with Waterfox G3 and Waterfox addons site/place for Waterfox language packages isn't ready yet.

I'm making language packages compatible with Waterfox G3, but only for Linux. You can use them also on Windows, but updating them might be problematic, cuz you'll need to that by manual, every time download, extract and install before updating Waterfox G3 (or just copy into waterfox-g3/browser/extensions).
